export const integrationMappings = [
  {
    baseEntity: "Cargos",
    source: "senior",
    entity: "Cargo",
    table: "dbo.Cargo",
    sourceColumns: ["CargoExternalId", "CargoId", "CargoName"],
    nextiColumn: "CargoIdNexti",
    dateColumns: ["Cargo_DataAcaoPend", "Cargo_DATCRI"],
    errorColumn: "Cargo_Erro",
    actionErrorColumn: "Cargo_AcaoErro",
  },
  {
    baseEntity: "Empresas",
    source: "neutral",
    entity: "Empresa",
    table: "dbo.Empresa",
    sourceColumns: ["EmpresaExternalId", "EmpresaId", "EmpresaNome"],
    nextiColumn: "EmpresaIdNexti",
    dateColumns: ["Empresa_DataAcaoPend"],
    errorColumn: "Empresa_Erro",
    actionErrorColumn: "Empresa_AcaoErro",
  },
  {
    baseEntity: "Escalas",
    source: "protheus",
    entity: "Escalas",
    table: "dbo.EscalasProtheus",
    sourceColumns: ["epp_ExternalId", "epp_codesc", "epp_nomesc"],
    nextiColumn: "epp_IdNexti",
    dateColumns: ["epp_DataAcaoPend"],
    errorColumn: "epp_Erro",
    actionErrorColumn: "epp_AcaoErro",
  },
  {
    baseEntity: "Horários",
    source: "protheus",
    entity: "Horários - Protheus",
    table: "dbo.HorarioProtheus",
    sourceColumns: ["hpp_ExternalId", "hpp_codhor", "hpp_deshor"],
    nextiColumn: "hpp_IdNexti",
    dateColumns: ["hpp_DataAcaoPend"],
    errorColumn: "hpp_Erro",
    actionErrorColumn: "hpp_AcaoErro",
  },
  {
    baseEntity: "Horários Escala",
    source: "protheus",
    entity: "Horários Escalas - Protheus",
    table: "dbo.HorariosEscalaProtheus",
    sourceColumns: ["hep_IdNexti"],
    nextiColumn: "hep_IdNexti",
    requiresNextiId: false,
    dateColumns: [],
    errorColumn: null,
    actionErrorColumn: null,
  },
  {
    baseEntity: "Sindicatos",
    source: "senior",
    entity: "Sindicato",
    table: "dbo.Sindicato",
    sourceColumns: ["Sindicato_IdNexti"],
    nextiColumn: "Sindicato_IdNexti",
    dateColumns: [],
    errorColumn: "Sindicato_Erro",
    actionErrorColumn: "Sindicato_AcaoErro",
  },
  {
    baseEntity: "Turmas",
    source: "protheus",
    entity: "Turma",
    table: "dbo.TurmaProtheus",
    sourceColumns: ["TurP_ExternalId", "TurP_codtma", "TurP_dessim"],
    nextiColumn: "TurP_IdNexti",
    dateColumns: ["TurP_DataAcaoPend", "TurP_datbas"],
    errorColumn: "TurP_Erro",
    actionErrorColumn: "TurP_AcaoErro",
  },
  {
    baseEntity: "Posto de Trabalho",
    source: "protheus",
    entity: "Posto de Trabalho",
    table: "dbo.PostoTrabalhoCarac",
    sourceColumns: ["ptc_IdNexti"],
    nextiColumn: "ptc_IdNexti",
    dateColumns: [],
    errorColumn: "ptc_Erro",
    actionErrorColumn: "ptc_AcaoErro",
  },
  {
    baseEntity: "Colaboradores",
    source: "protheus",
    entity: "Colaborador - Protheus",
    table: "dbo.ColaboradorProtheus",
    sourceColumns: ["ColabP_externalId", "ColabP_Numcad", "ColabP_nomfun"],
    nextiColumn: "ColabP_IdNexti",
    dateColumns: ["ColabP_DataAcaoPend", "ColabP_datadm"],
    errorColumn: "ColabP_Erro",
    actionErrorColumn: "ColabP_AcaoErro",
  },
  {
    baseEntity: "Colaboradores",
    source: "senior",
    entity: "Colaboradores",
    table: "dbo.ColaboradorSenior",
    sourceColumns: ["Colab_IdNexti"],
    nextiColumn: "Colab_IdNexti",
    dateColumns: [],
    errorColumn: "Colab_Erro",
    actionErrorColumn: "Colab_AcaoErro",
  },
  {
    baseEntity: "Lista Ausência",
    source: "protheus",
    entity: "Lista Ausência - Protheus",
    table: "dbo.ListaAusenciaProtheus",
    sourceColumns: ["lap_externalId", "lap_numcad", "lap_sitafa"],
    nextiColumn: "lap_IdNexti",
    dateColumns: ["lap_DataAcaoPend", "lap_datafa"],
    errorColumn: "lap_Erro",
    actionErrorColumn: "lap_AcaoErro",
    statusColumn: "lap_status",
  },
  {
    baseEntity: "Dependentes",
    source: "protheus",
    entity: "Dependentes - Protheus",
    table: "dbo.DependentesProtheus",
    sourceColumns: [],
    nextiColumn: null,
    dateColumns: [],
    errorColumn: null,
    actionErrorColumn: null,
  },
  {
    baseEntity: "Situações",
    source: "protheus",
    entity: "Situações",
    table: "dbo.SituacoesProtheus",
    sourceColumns: ["SitPro_SituacaoNexti", "SitPro_IdNexti"],
    nextiColumn: "SitPro_IdNexti",
    dateColumns: [],
    errorColumn: "SitPro_Erro",
    actionErrorColumn: "SitPro_AcaoErro",
  },
  {
    baseEntity: "Histórico Sindicato",
    source: "protheus",
    entity: "Histórico Sindicato - Protheus",
    table: "dbo.HistSindProtheus",
    sourceColumns: ["hsp_idnexti"],
    nextiColumn: "hsp_idnexti",
    dateColumns: [],
    errorColumn: "hsp_Erro",
    actionErrorColumn: "hsp_AcaoErro",
  },
  {
    baseEntity: "Tomador",
    source: "protheus",
    entity: "Tomador",
    table: "dbo.TomadorProtheus",
    sourceColumns: ["TOMP_ExternalID", "TOMP_codoem", "TOMP_nomoem"],
    nextiColumn: "TOMP_idnexti",
    dateColumns: ["TOMP_DataAcaoPend", "TOMP_DtMan"],
    errorColumn: "TOMP_Erro",
    actionErrorColumn: "TOMP_AcaoErro",
  },
  {
    baseEntity: "Marcação Horários",
    source: "protheus",
    entity: "Marcação Horários - Protheus",
    table: "dbo.MarcacoesHorarioProtheus",
    sourceColumns: ["mhfP_IdNexti"],
    nextiColumn: "mhfP_IdNexti",
    requiresNextiId: false,
    dateColumns: [],
    errorColumn: null,
    actionErrorColumn: null,
  },
  {
    baseEntity: "Troca Posto",
    source: "protheus",
    entity: "Troca Posto - Protheus",
    table: "dbo.TrocaPostoProtheus",
    sourceColumns: ["TPP_NumCad_Fun", "TPP_PosTra_Pos"],
    nextiColumn: "TPP_IdNexti",
    dateColumns: ["TPP_DataAcaoPend", "TPP_DataTroca"],
    errorColumn: "TPP_Erro",
    actionErrorColumn: "TPP_AcaoErro",
  },
  {
    baseEntity: "Troca Escala",
    source: "protheus",
    entity: "Troca Escala - Protheus",
    table: "dbo.TrocaEscala",
    sourceColumns: ["tep_IdNexti"],
    nextiColumn: "tep_IdNexti",
    dateColumns: [],
    errorColumn: "tep_Erro",
    actionErrorColumn: "tep_AcaoErro",
  },
  {
    baseEntity: "Unidade Negócio",
    source: "senior",
    entity: "Unidade de Negócios",
    table: "dbo.UnidadeNegSenior",
    sourceColumns: ["UniNegSen_ExId", "UniNegSen_Cod", "UniNegSen_Nom"],
    nextiColumn: "UniNegSen_IdNexti",
    dateColumns: ["UniNegSen_DataAcaoPend"],
    errorColumn: "UniNegSen_Erro",
    actionErrorColumn: "UniNegSen_AcaoErro",
  },
];
